name: "Cache & Restore node modules"
description: "Cache & Restore node modules"

runs:
  using: "composite"
  steps:
    - run: echo "🔎 The name of your branch is ${{ github.head_ref }} and your repository is ${{ github.repository }}."
      shell: sh

    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Cache dependencies
      id: cache
      uses: actions/cache@v2
      with:
        path: node_modules
        key: modules-${{ hashFiles('yarn.lock') }}

    - name: Install dependencies
      shell: sh
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile