name: Stop NX Cloud Agents

on:
  workflow_call:

jobs:
  stop-agents:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dependencies
        uses: ./.github/actions/cache-node-modules
      - name: Start Nx Agent ${{ matrix.agent }}
        run: yarn nx-cloud stop-all-agents