name: Start NX Cloud Agents

on:
  workflow_call:

jobs:
  agents:
    name: NX Cloud Agent
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        agent: [1, 2, 3]
    steps:
      - uses: actions/checkout@v2
      - name: Setup dependencies
        uses: ./.github/actions/cache-node-modules
      - name: Start Nx Agent ${{ matrix.agent }}
        run: npx nx-cloud start-agent
