name: Start NX Cloud CI Run

on:
  workflow_call:

jobs:
  start-ci-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dependencies
        uses: ./.github/actions/cache-node-modules
      - name: Start Nx Agent ${{ matrix.agent }}
        run: yarn @nrwl/nx-cloud start-ci-run
