name: Install & Cache NPM modules

on:
  workflow_call:
    
jobs:
  setup:
    name: cache & install dependencies
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔎 The name of your branch is ${{ github.head_ref }} and your repository is ${{ github.repository }}."

      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup dependencies
        uses: ./.github/actions/cache-node-modules
        
